groups:
- name: alert.rules
  rules:

  # Instance Down Alert
  - alert: InstanceDown
    expr: up == 0
    for: 1m
    annotations:
      title: 'Instance {{ $labels.instance }} down'
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute.'
    labels:
      severity: 'critical'

  # Host Out of Memory Alert
  - alert: HostOutOfMemory
    expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100 < 10
    for: 1m
    annotations:
      title: 'Host out of memory (instance {{ $labels.instance }})'
      description: 'Node memory is filling up (< 10% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}'
    labels:
      severity: 'warning'

  # Host High CPU Load Alert
  - alert: HostHighCpuLoad
    expr: (1 - avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[1m]))) * 100 > 80
    for: 1m
    annotations:
      title: 'Host high CPU load (instance {{ $labels.instance }})'
      description: 'CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}'
    labels:
      severity: 'warning'

  # Host Out of Disk Space Alert
  - alert: HostOutOfDiskSpace
    expr: (node_filesystem_avail_bytes{mountpoint="/"} * 100) / node_filesystem_size_bytes{mountpoint="/"} < 10
    for: 1m
    annotations:
      title: 'Host out of disk space (instance {{ $labels.instance }})'
      description: 'Disk is almost full (< 10% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}'
    labels:
      severity: 'warning'

  # High CPU Usage Alert
  - alert: HighCPUUsage
    expr: avg(rate(node_cpu_seconds_total{mode="system"}[1m])) * 100 > 80
    for: 1m
    annotations:
      summary: "High CPU usage on instance {{ $labels.instance }}"
      description: "CPU usage has been over 80% for 1 minute on instance {{ $labels.instance }}"
    labels:
      severity: 'critical'