global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/prometheus-rules.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.1.10:9090', '192.168.1.12:9090', '192.168.1.13:9090', '192.168.1.14:9090', '192.168.1.15:9090']
  # Add more jobs if needed
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.1.15:9100', '192.168.1.16:9100', '192.168.1.12:9100', '192.168.1.10:9100', '192.168.1.14:9100']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - '192.168.1.12:9093'