version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3002:3000"  # Map host port 3002 to container port 3000
    volumes:
      - /grafana/grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Change this to a strong password
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9091:9090"  # Map host port 9091 to container port 9090
    volumes:
      - /prometheus/prometheus-data:/prometheus
      - /prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

volumes:
  grafana-data:
  prometheus-data: